version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: openjdk:17
    container_name: springboot-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["sh", "-c", "cd /app && ./mvnw spring-boot:run"]
    depends_on:
      - db

volumes:
  db_data:
